baseurl = "https://elhoucine.github.io/"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Elhoucine Azayou"
title = "Elhoucine Azayou offcial website"
pygmentsuseclasses = true
#disqusShortname = "elhoucine" # TODO: optional, comment out to disable Disqus
pluralizelisttitles = false
theme = "cocoa"

# Enable Emoji emoticons support for page content.
# See www.emoji-cheat-sheet.com
enableEmoji = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
Author = "Elhoucine Azayou"
CacheBuster = true
DateForm = "Jan 02, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
Description = "Don't panic, elhoucine Azayou's official virtual mind."
Email = "houcineparade@gmail.com"
FaviconFile = "img/leaf.ico"
# GATracker = "XYZ" # TODO:
GitHub = "//github.com/elhoucine"
Initials = "ad" # displayed on single post page; DEPRECATED in v0.3.0
Lang = "en"
# LinkedIn = "//linkedin.com/in/you" # TODO:
Twitter = "//twitter.com/elhoucineaz" # TODO:
ExtraCssFiles = [ "/css/override.css" ] # relative to public directory
